# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: #
    hikari:
      maximum-pool-size: 10
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      time-between-eviction-runs-millis: 1000
      min-evictable-idle-time-millis: 1000
  mvc:
    # 静态资源会加载到/res/下的路由下
    static-path-pattern: [/upload/blog/Img/**, /upload/user/avatar/**]  # 打开这个欢迎页会失效， 会影响网站图标功能
  resources:
    # 静态资源位置
    static-locations: [classpath:/upload/blog/Img/, classpath:/upload/user/avatar/]
  servlet:
    # 上传下载设置
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    multipart:
    location: /data/upload_tmp
  # 配置Redis
  redis:
    host: 
    port: 3401
    database: 0
    timeout: 5000
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0
    password: xc123
  # 监控页面client
  boot:
    admin:
      client:
        instance:
          prefer-ip: true #开启以ip为url
        url: http://localhost:3334
management:
  endpoints:
    enabled-by-default: true # 默认开启所有端点
    web:
      exposure:
        include: '*' # 以web方式暴露所有
  endpoint:
    health:
      show-details: always # 显示详细信息， 默认不开启


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 3333
shiro:
  jwt:
    secret:     # 有效时长 7天，单位秒
    expire: 604800
    header: token

shiro-redis:
  enable: true
  redis-manager:
    host: ----:3401
    password: 
localhost:
  ip-address: ----
  # 日志
logging:
  level:
     com:
       alibaba:
         druid:
           pool:
             DruidDataSource: debug
# debug: true

#腾讯云api秘钥id
tencent:
  yun:
    secret-id: #
    secret-key: #
    storage-bucket: #
    place: ap-nanjing
